// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZH560Jcc9Qi2L2n5YSlYg2QjzTVeg5w',
    appId: '1:246959584592:web:c563e9ecb58e288f002855',
    messagingSenderId: '246959584592',
    projectId: 'ieee-event-app',
    authDomain: 'ieee-event-app.firebaseapp.com',
    storageBucket: 'ieee-event-app.appspot.com',
    measurementId: 'G-FZZ3D5QT8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRad8pQ_KlGfNJS77K33MuURr0BxFOW9k',
    appId: '1:246959584592:android:38fd9403d23c5827002855',
    messagingSenderId: '246959584592',
    projectId: 'ieee-event-app',
    storageBucket: 'ieee-event-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9KvjlNKIWu1TEL7meiGuEsa9z5h3Xn38',
    appId: '1:246959584592:ios:b722726e752fc53a002855',
    messagingSenderId: '246959584592',
    projectId: 'ieee-event-app',
    storageBucket: 'ieee-event-app.appspot.com',
    iosBundleId: 'com.example.appTemplate',
  );
}
